# List all source files the application uses.
APPLICATION_SRCS = main.c  nrf_delay.c

PROJECT_NAME = blinky

DEVICE = NRF51
BOARD = BOARD_PCA10001
#SEGGER_SERIAL = 

#USE_SOFTDEVICE = S110

SDK_PATH = $(HOME)/lib/sdk//nrf51822/
TEMPLATE_PATH = ./template/

CFLAGS = -Os

GDB_PORT_NUMBER = 2331

include $(TEMPLATE_PATH)Makefile
