TARGET_CHIP := NRF51822_QFAA_CA
BOARD := BOARD_PCA10001
DEVICE := NRF51

C_SOURCE_FILES += main_tx.c
C_SOURCE_FILES += radio_config.c
C_SOURCE_FILES += simple_uart.c
C_SOURCE_FILES += nrf_delay.c

OUTPUT_NAME := ble_ann
SDK_PATH = ../../../../

SDK_PATH = $(HOME)/lib/sdk/nrf51822/
TEMPLATE_PATH = ../template/

include $(TEMPLATE_PATH)Makefile
